cc_binary(
  name = "lsh_example",
  srcs = [
    'lsh_example.cpp',
  ],

  incs = [
    '../falconn_mips',
    '../falconn_mips/src/include',
    '../falconn_mips/external/eigen',
    # '../../thirdparty/falconn_mips',
    # '../thirdparty/lsh_mips/falconn_mips/src/include',
  ],

  cxxflags = [
    '-std=c++11',
  ],
)

cc_binary(
  name = "mips_example",
  srcs = [
    'mips_example.cpp',
  ],

  incs = [
    '../falconn_mips',
    '../falconn_mips/src/include',
    '../falconn_mips/external/eigen',
    # '../../thirdparty/falconn_mips',
    # '../thirdparty/lsh_mips/falconn_mips/src/include',
  ],

  cxxflags = [
    '-O0',
    '-std=c++11',
  ],
)