cc_binary(
  name = "lsh_main",
  srcs = [
    'main.cpp',
    'lsh.cpp',
    'lsh_wrapper.cpp',
    'lsh_tester.cpp',
  ],

  incs = [
    '.',
    '../../../falconn_mips/external/eigen',
  ],

)

cc_library(
  name = 'lsh_mips',
  srcs = [
    'lsh.cpp',
  ],

  incs = [
    '.',
    '../../../falconn_mips/external/eigen',
  ],
)
